# Generated by Django 6.0.5 on 2026-05-15 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('file_url', models.CharField(max_length=2048)),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.IntegerField()),
                ('is_deleted', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'media',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NoteCollaborators',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('is_pinned', models.IntegerField()),
                ('is_archived', models.IntegerField()),
                ('is_trashed', models.IntegerField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'note_collaborators',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('content', models.JSONField(blank=True, null=True)),
                ('content_text', models.TextField(blank=True, null=True)),
                ('type', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('is_pinned', models.IntegerField()),
                ('is_archived', models.IntegerField()),
                ('is_trashed', models.IntegerField()),
                ('is_deleted', models.IntegerField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('position', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('server_updated_at', models.DateTimeField()),
                ('client_updated_at', models.DateTimeField()),
                ('trashed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NoteTags',
            fields=[
                ('pk', models.CompositePrimaryKey('note_id', 'tag_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.IntegerField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'note_tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NoteVersionEditors',
            fields=[
                ('pk', models.CompositePrimaryKey('version_id', 'user_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'note_version_editors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NoteVersions',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('content', models.JSONField(blank=True, null=True)),
                ('saved_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'note_versions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=21)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('is_read', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'notifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OtpVerifications',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('otp_hash', models.CharField(max_length=512)),
                ('purpose', models.CharField(max_length=14)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'otp_verifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefreshTokens',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=512)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'refresh_tokens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reminders',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('remind_at', models.DateTimeField()),
                ('repeat_type', models.CharField(max_length=7)),
                ('is_notified', models.IntegerField()),
                ('is_deleted', models.IntegerField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'reminders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResetTokens',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=512)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'reset_tokens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_deleted', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TodoItems',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('is_completed', models.IntegerField()),
                ('position', models.CharField(max_length=255)),
                ('remind_at', models.DateTimeField(blank=True, null=True)),
                ('repeat_type', models.CharField(max_length=7)),
                ('is_notified', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'todo_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.CharField(blank=True, max_length=512, null=True)),
                ('status_token', models.CharField(blank=True, max_length=50, null=True)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('is_verified', models.IntegerField()),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.users')),
                ('theme', models.CharField(max_length=6)),
                ('notifications_enabled', models.IntegerField()),
                ('notify_reminder', models.IntegerField()),
                ('notify_collaboration', models.IntegerField()),
                ('default_note_view', models.CharField(max_length=4)),
                ('sort_by', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_settings',
                'managed': False,
            },
        ),
    ]
