"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

# myproject/settings.py
# ─────────────────────────────────────────────────────────────────────────────
 
from pathlib import Path
from datetime import timedelta
import os
 
BASE_DIR = Path(__file__).resolve().parent.parent
 
SECRET_KEY = 'django-insecure-+!u=*6obvivbwmaqu&qwv%)ty4*_h55dc0k3wd1^u8v)r0_^7='
 
DEBUG = True
 
ALLOWED_HOSTS = ['*']   # Cho phép máy ảo Android / thiết bị thật kết nối
 
# ─────────────────────────────────────────────────────────────────────────────
# APPS
# ─────────────────────────────────────────────────────────────────────────────
 
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',          # CORS cho Expo
    'myapp',
]
 
# ─────────────────────────────────────────────────────────────────────────────
# MIDDLEWARE
# corsheaders PHẢI đứng đầu
# ─────────────────────────────────────────────────────────────────────────────
 
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',    # ← đầu tiên
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
 
ROOT_URLCONF = 'myproject.urls'
 
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
 
WSGI_APPLICATION = 'myproject.wsgi.application'
 
# ─────────────────────────────────────────────────────────────────────────────
# DATABASE — MySQL
# ─────────────────────────────────────────────────────────────────────────────
 
DATABASES = {
    'default': {
        'ENGINE':   'django.db.backends.mysql',
        'NAME':     'mindraft_db',
        'USER':     'root',
        'PASSWORD': '123456',
        'HOST':     'localhost',
        'PORT':     '3306',
    }
}
 
# ─────────────────────────────────────────────────────────────────────────────
# CACHE — dùng để lưu trạng thái "đã verify OTP reset_password"
# Mặc định LocMemCache (dev). Production nên đổi sang Redis.
# ─────────────────────────────────────────────────────────────────────────────
 
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}
 
# ─────────────────────────────────────────────────────────────────────────────
# DRF + JWT
# ─────────────────────────────────────────────────────────────────────────────
 
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}
 
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME':    timedelta(days=1),      # Giữ nguyên như cài đặt gốc
    'REFRESH_TOKEN_LIFETIME':   timedelta(days=7),
    'AUTH_HEADER_TYPES':        ('Bearer',),
    'ROTATE_REFRESH_TOKENS':    True,
    'BLACKLIST_AFTER_ROTATION': True,
}
 
# ─────────────────────────────────────────────────────────────────────────────
# EMAIL — Console backend (OTP in ra terminal khi dev)
# Để dùng SMTP thật: đổi EMAIL_BACKEND và điền các thông số bên dưới
# ─────────────────────────────────────────────────────────────────────────────
 
 
# settings.py

# 1. Chế độ gửi mail qua Server thật (SMTP)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# 2. Cấu hình máy chủ Gmail
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# 3. Tài khoản "Tổng đài" của ông
EMAIL_HOST_USER = 'quannhiep91@gmail.com' 

# 4. Mật khẩu ứng dụng (Viết liền, không dấu cách)
EMAIL_HOST_PASSWORD = 'shozkdjopendhcsw' 

# 5. Tên hiển thị khi người dùng nhận được mail
DEFAULT_FROM_EMAIL = 'Mindraft <quannhiep91@gmail.com>'
 
# ─────────────────────────────────────────────────────────────────────────────
# CORS — Expo Web (8081) + máy ảo Android (10.0.2.2)
# ─────────────────────────────────────────────────────────────────────────────
 # settings.py

# 1. Cho phép các phương thức (đã có thì thôi)
CORS_ALLOW_METHODS = [
    "DELETE", "GET", "OPTIONS", "PATCH", "POST", "PUT",
]

# 2. QUAN TRỌNG NHẤT: Cho phép cái header 'x-platform' của ông
from corsheaders.defaults import default_headers

CORS_ALLOW_HEADERS = list(default_headers) + [
    "x-platform", # Thêm thằng này vào để hết lỗi đỏ
]

# 3. Đảm bảo dòng này vẫn là True
CORS_ALLOW_ALL_ORIGINS = True
# api.ts dùng SecureStore (không phải Cookie) nên CORS_ALLOW_CREDENTIALS
# không bắt buộc, nhưng để sẵn cho trường hợp dùng web browser
CORS_ALLOW_CREDENTIALS = True
 
# ─────────────────────────────────────────────────────────────────────────────
# MISC
# ─────────────────────────────────────────────────────────────────────────────
 
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]
 
LANGUAGE_CODE    = 'en-us'
TIME_ZONE        = 'UTC'
USE_I18N         = True
USE_TZ           = True
STATIC_URL       = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'